server:
  port: 8001 # 指定Eureka实例的端口
  servlet:
    context-path: /user # 设置项目访问路径,访问路径为：http://localhost:8000/smbmsprovider,如果不配置则访问路径为http://localhost:8000
    jsp:
      init-parameters:
        development: true # 修改JSP之后立即加载 server.jsp-servlet.init-parameters.development=true
eureka:
  instance:
    prefer-ip-address: true # 是否显示主机IP
  client:
    service-url:
      defaultzone:
        http://localhost:8761/eureka/ # 指定Eureka服务端地址
spring:
  application:
    name: eurekauser #指定应用名称
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: root

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
#    user: root
#    password: 123
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
      timeout: 5000

  # jsp配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
  thymeleaf:
    cache: false
    enabled: false
  devtools:
    restart:
      enabled: true

# 配置mapper映射文件位置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml # mapper映射文件
# log4j2配置：自定义log4j2配置
logging:
  config:
    classpath: log4j2.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
debug: true

